routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardPostController;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function () {
    return view("home", ["title" => "Home", "active" => "home"]);
})->name("home");

Route::get("/posts", [PostController::class, "index"])->name("posts");
Route::get("/posts/{post:slug}", [PostController::class, "detail"])->name('posts.detail');

Route::get("/category", [CategoryController::class, "index"])->name("category");

Route::prefix("dashboard")
    ->middleware(["auth:sanctum", "verified"])
    ->group(function () {
        Route::get("/", [DashboardController::class, "index"])->name("dashboard");
        Route::resource("posts", DashboardPostController::class);
    });
Route::prefix("dashboard")
    ->middleware('admin')
    ->group(function () {
        Route::resource("categories", AdminCategoryController::class)->except("show");
        Route::resource("all-posts", AdminPostController::class)->only([
            "index", "destroy", "show"
        ]);
    });

Route::get("/about", function () {
    return view("about");
});

// Route::middleware(["auth:sanctum", "verified"])
//     ->get("/dashboard", function () {
//         return view("dashboard");
//     })
//     ->name("dashboard");


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ["id"];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function getRouteKeyName()
    {
        return "slug";
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("pages.frontend.categories", [
            "title" => "Category",
            "active" => "categories",
            "categories" => Category::all(),
        ]);
    }
}

resources/views/pages/dashboard/admin/categories/create.blade.php
@extends('pages.dashboard.index')
@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Tambah Kategori</h1>
    <a href="{{ route('categories.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-backward fa-sm text-white-50"></i> Back
    </a>
  </div>

  <!-- Content Row -->
  @if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
  @endif

  <div class="card shadow mb-4">
    <div class="card-body">
      <form action="{{ route('categories.store') }}" method="POST">
        @csrf
        <div class="form-group">
          <label for="name">Category name</label>
          <input type="text" class="form-control" name="name" placeholder="Category name" required
            value="{{ old('name') }}">
        </div>
        <button type="submit" class="btn btn-primary">
          Simpan
        </button>
      </form>
    </div>
  </div>

</div>
@endsection

resources/views/pages/dashboard/admin/categories/edit.blade.php
@extends('pages.dashboard.index')

@section('title')
Edit Category {{ $category->name }}
@endsection

@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Edit Kategori</h1>
    <a href="{{ route('categories.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-backward fa-sm text-white-50"></i> Back
    </a>
  </div>

  <!-- Content Row -->
  @if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
  @endif

  <div class="card shadow mb-4">
    <div class="card-body">
      <form action="{{ route('categories.update', $category->slug)}}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-group">
          <label for="name">Category name</label>
          <input type="text" class="form-control" name="name" placeholder="Category name"
            value="{{ old('name', $category->name)  }}" required>
        </div>
        <button type="submit" class="btn btn-primary">
          Ubah
        </button>
      </form>
    </div>
  </div>

</div>
@endsection

resources/views/pages/dashboard/admin/categories/index.blade.php
@extends('pages.dashboard.index')

@section('title')
All Category
@endsection

@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kategori</h1>
    <a href="{{ route('categories.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-plus fa-sm text-white-50"></i> Tambah kategori
    </a>
  </div>

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>ID</th>
              <th>Category Name</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($categories as $category)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{ $category->name }}</td>
              <td>
                <a href="{{ route('categories.edit', $category->slug) }}" class="btn btn-info">
                  <i class="fa fa-pencil-alt"></i>
                </a>
                <form action="{{ route('categories.destroy', $category->slug) }}" method="post" class="d-inline">
                  @csrf
                  @method('delete')
                  <button class="btn btn-danger" onclick="return confirm('Apakah anda Yakin?')">
                    <i class="fa fa-trash"></i>
                  </button>
                </form>

              </td>
            </tr>
            @empty
            <td colspan="3" class="text-center">
              Data Kosong
            </td>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
@endsection