routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardPostController;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function () {
    return view("home", ["title" => "Home", "active" => "home"]);
})->name("home");

Route::get("/posts", [PostController::class, "index"])->name("posts");
Route::get("/posts/{post:slug}", [PostController::class, "detail"])->name('posts.detail');

Route::get("/category", [CategoryController::class, "index"])->name("category");

Route::prefix("dashboard")
    ->middleware(["auth:sanctum", "verified"])
    ->group(function () {
        Route::get("/", [DashboardController::class, "index"])->name("dashboard");
        Route::resource("posts", DashboardPostController::class);
    });
Route::prefix("dashboard")
    ->middleware('admin')
    ->group(function () {
        Route::resource("categories", AdminCategoryController::class)->except("show");
        Route::resource("all-posts", AdminPostController::class)->only([
            "index", "destroy", "show"
        ]);
    });

Route::get("/about", function () {
    return view("about");
});

// Route::middleware(["auth:sanctum", "verified"])
//     ->get("/dashboard", function () {
//         return view("dashboard");
//     })
//     ->name("dashboard");


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = ["id"];
    protected $with = ["user", "category"];

    public function scopeFilter($query, array $filters)
    {
        $query->when($filters["search"] ?? false, function ($query, $search) {
            return $query->where(function ($query) use ($search) {
                $query
                    ->where("title", "like", "%" . $search . "%")
                    ->orWhere("body", "like", "%" . $search . "%");
            });
        });

        $query->when($filters["category"] ?? false, function (
            $query,
            $category
        ) {
            return $query->whereHas("category", function ($query) use (
                $category
            ) {
                return $query->where("slug", $category);
            });
        });

        $query->when($filters["user"] ?? false, function ($query, $user) {
            return $query->whereHas("user", function ($query) use ($user) {
                return $query->where("username", $user);
            });
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getRouteKeyName()
    {
        return "slug";
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\User;

class DashboardController extends Controller
{
    public function index()
    {
        return view("pages.dashboard", [
            "post" => Post::count(),
            "category" => Category::count(),
            "user" => User::where("is_admin", false)->count(),
            "admin" => User::where("is_admin", true)->count()
        ]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $title = "";
        if (request("category")) {
            $category = Category::firstWhere("slug", request("category"));
            $title = " in " . $category->name;
        }
        if (request("user")) {
            $user = User::firstWhere("username", request("user"));
            $title = " by " . $user->name;
        }
        return view("pages.frontend.posts", [
            "title" => "All Posts" . $title,
            "active" => "posts",
            "posts" => Post::latest()
                ->filter(request(["search", "category", "user"]))
                ->paginate(7)
                ->withQueryString(),
        ]);
    }

    public function detail(Post $post)
    {
        return view("pages.frontend.detail-post", [
            "title" => "Detail Post",
            "active" => "posts",
            "post" => $post,
        ]);
    }
}

resources/views/pages/dashboard/posts/create.blade.php
@extends('pages.dashboard.index')

@section('title')
Tambah Post
@endsection

@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Tambah Post</h1>
    <a href="{{ route('posts.index') }}" class="btn btn-primary">
      <i class="fas fa-backward text-white-50"></i> Back
    </a>
  </div>

  <!-- Content Row -->

  <div class="card shadow mb-4">
    <div class="card-body">
      <form action="{{ route('posts.store') }}" method="POST" class="mb-5" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
            placeholder="Title" value="{{ old('title') }}">
          @error('title')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
          @enderror
        </div>
        <div class="form-group">
          <label for="category">Kategori</label>
          <select name="category_id" required class="form-control">
            @foreach($categories as $category)
            <option value="{{ $category->id }}" {{ old('category_id')==$category->id ? 'selected' : '' }}>
              {{ $category->name }}
            </option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="image" class="form-label">Post Image</label>
          <img class="img-preview img-fluid mb-3 col-sm-5 d-block">
          <input class="form-control-file @error('image') is-invalid @enderror" type="file" id="image" name="image"
            onchange="previewImage()">
          @error('image')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
          @enderror
        </div>
        <label for="body">Body</label>
        @error('body')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <input id="body" type="hidden" name="body" value="{{ old('body') }}">
        <trix-editor input="body"></trix-editor>
        <button type="submit" class="btn btn-primary mt-3">
          Simpan
        </button>
      </form>
    </div>
  </div>

</div>
@include('layouts.partials.dashboard.script')
@endsection

resources/views/pages/dashboard/posts/edit.blade.php
@extends('pages.dashboard.index')

@section('title')
Edit Post {{ $post->title }}
@endsection

@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Edit Post</h1>
    <a href="{{ route('posts.index') }}" class="btn btn-primary">
      <i class="fas fa-backward text-white-50"></i> Back
    </a>
  </div>

  <!-- Content Row -->

  <div class="card shadow mb-4">
    <div class="card-body">
      <form action="{{ route('posts.update', $post->slug) }}" method="POST" class="mb-5" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title"
            placeholder="Title" value="{{ old('title', $post->title) }}">
          @error('title')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
          @enderror
        </div>
        <div class="form-group">
          <label for="category">Kategori</label>
          <select name="category_id" required class="form-control">
            @foreach($categories as $category)
            <option value="{{ $category->id }}" {{ old('category_id', $post->category_id)==$category->id ? 'selected' :
              '' }}>
              {{ $category->name }}
            </option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="image" class="form-label">Post Image</label>
          <img class="img-preview img-fluid mb-3 col-sm-5 d-block"
            src="{{ $post->image ? asset('storage/' . $post->image) : '' }}">
          <input class="form-control-file @error('image') is-invalid @enderror" type="file" id="image" name="image"
            onchange="previewImage()">
          @error('image')
          <div class="invalid-feedback">
            {{ $message }}
          </div>
          @enderror
        </div>
        <label for="body">Body</label>
        @error('body')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <input id="body" type="hidden" name="body" value="{{ old('body', $post->body) }}">
        <trix-editor input="body"></trix-editor>
        <button type="submit" class="btn btn-primary mt-3">
          Simpan
        </button>
      </form>
    </div>
  </div>

</div>
@include('layouts.partials.dashboard.script')
@endsection

resources/views/pages/dashboard/posts/index.blade.php
@extends('pages.dashboard.index')

@section('title')
My Posts
@endsection

@section('contents')
<!-- Page Heading -->

<div class="container-fluid">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">My Posts</h1>
    <a href="{{ route('posts.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Post
    </a>
  </div>

  @if (session()->has('success'))
  <div class="alert alert-success" role="alert">
    {{ session('success') }}
  </div>
  @endif

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>No</th>
              <th>Judul</th>
              <th>Kategori</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($posts as $post)
            <tr>
              <td>{{ $loop->iteration }}</td>
              <td>{{ $post->title }}</td>
              <td>{{ $post->category->name }}</td>
              <td>
                <a href="{{ route('posts.show', $post->slug) }}" class="btn btn-info">
                  <i class="fa fa-eye"></i>
                </a>
                <a href="{{ route('posts.edit', $post->slug) }}" class="btn btn-warning">
                  <i class="fa fa-pencil-alt"></i>
                </a>
                <form action="{{ route('posts.destroy', $post->slug) }}" method="post" class="d-inline">
                  @csrf
                  @method('delete')
                  <button class="btn btn-danger" onclick="return confirm('Apakah anda Yakin?')">
                    <i class="fa fa-trash"></i>
                  </button>
                </form>

              </td>
            </tr>
            @empty
            <td colspan="4" class="text-center">
              Data Kosong
            </td>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>
@endsection

resources/views/pages/dashboard/posts/show.blade.php
@extends('pages.dashboard.index')

@section('title')
{{ $post->title }}
@endsection

@section('contents')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <h3>{{ $post->title }}</h3>
      <a href="{{ route('posts.index') }}" class="btn btn-primary">
        <i class="fas fa-backward text-white-50"></i> Back
      </a>
      <a href="{{ route('posts.edit', $post->slug) }}" class="btn btn-warning">
        <i class="fa fa-pencil-alt"></i> Edit
      </a>
      <form action="{{ route('posts.destroy', $post->slug) }}" method="post" class="d-inline">
        @csrf
        @method('delete')
        <button class="btn btn-danger">
          <i class="fa fa-trash"></i> Delete
        </button>
      </form>
      @if ($post->image)
      <div style="max-height: 400px; overflow: hidden;">
        <img src="{{ asset('storage/'.$post->image) }}" alt="{{ $post->title }}" class="img-fluid mt-3">
      </div>
      @else
      <img src="https://source.unsplash.com/1200x400?{{ $post->category->name }}" class="card-img-top mt-3"
        alt="{{ $post->category->name }}">
      @endif
      <div class="mt-3">
        {!! $post->body !!}
      </div>
    </div>
  </div>
</div>
@endsection