routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardPostController;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function () {
    return view("home", ["title" => "Home", "active" => "home"]);
})->name("home");

Route::get("/posts", [PostController::class, "index"])->name("posts");
Route::get("/posts/{post:slug}", [PostController::class, "detail"])->name('posts.detail');

Route::get("/category", [CategoryController::class, "index"])->name("category");

Route::prefix("dashboard")
    ->middleware(["auth:sanctum", "verified"])
    ->group(function () {
        Route::get("/", [DashboardController::class, "index"])->name("dashboard");
        Route::resource("posts", DashboardPostController::class);
    });
Route::prefix("dashboard")
    ->middleware('admin')
    ->group(function () {
        Route::resource("categories", AdminCategoryController::class)->except("show");
        Route::resource("all-posts", AdminPostController::class)->only([
            "index", "destroy", "show"
        ]);
    });

Route::get("/about", function () {
    return view("about");
});

// Route::middleware(["auth:sanctum", "verified"])
//     ->get("/dashboard", function () {
//         return view("dashboard");
//     })
//     ->name("dashboard");


// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\User;

class DashboardController extends Controller
{
    public function index()
    {
        return view("pages.dashboard", [
            "post" => Post::count(),
            "category" => Category::count(),
            "user" => User::where("is_admin", false)->count(),
            "admin" => User::where("is_admin", true)->count()
        ]);
    }
}

resources/views/layouts/partials/dashboard/logout-modal.blade.php
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{{ route('login') }}">Logout</a>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/partials/dashboard/navbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name
          }}</span>
        <img class="img-profile rounded-circle" src="https://ui-avatars.com/api/?name={{ Auth::user()->username
									}}">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <form method="POST" action="{{ route('logout') }}">
          @csrf
          <a class="dropdown-item" href="{{ route('logout') }}"
            onclick="event.preventDefault();this.closest('form').submit();" data-toggle="modal"
            data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </form>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

resources/views/layouts/partials/dashboard/script.blade.php
<script>
  function previewImage() {
    const image = document.querySelector('#image');
    const imgPreview = document.querySelector('.img-preview');

    const blob = URL.createObjectURL(image.files[0]);
    imgPreview.src = blob;
  }
</script>

resources/views/layouts/partials/dashboard/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href={{ route('posts') }}>
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item {{ request()->routeIs('dashboard') ? 'active' : '' }}">
    <a class="nav-link" href="/dashboard">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Master
  </div>
  <!-- Nav Item - My Posts -->
  <li class="nav-item {{ request()->routeIs('posts.*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('posts.index') }}">
      <i class="fas fa-fw fa-file"></i>
      <span>My Posts</span></a>
  </li>

  @can('admin')
  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Administrator
  </div>
  <!-- Nav Item - Categories -->
  <li class="nav-item {{ request()->routeIs('categories.*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('categories.index') }}">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Categories</span></a>
  </li>
  <li class="nav-item {{ request()->routeIs('all-posts.*') ? 'active' : '' }}">
    <a class="nav-link" href="{{ route('all-posts.index') }}">
      <i class="fas fa-fw fa-file"></i>
      <span>All Posts</span></a>
  </li>
  @endcan
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->